EMS/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include('EMS_app.urls', namespace='EMS')),

]

EMS_app/urls.py
from django.urls import path

from . import views

app_name = 'EMS'
# url patterns has list of all urls corresponding to the views and the webpages
urlpatterns = [
    path('', views.main, name='main'),
    path('login/organizer', views.login_page_organizer, name = 'login_page_organizer'),
    path('login/participant', views.login_page_participant, name = 'login_page_participant'),
    path('event_view/<int:event_id>/', views.event_view, name='event_view'),
    # path('logout/', views.logout_page, name= 'logout'),
    path('register/', views.register, name='register'),
    path('home/', views.home_page, name='home_page'),
    path('event_registration/', views.event_registration, name='event_registration'),
    path('event_edit/<int:id>', views.event_edit, name='event_edit'),
    path('delete_event/<int:id>', views.delete_event, name='delete_event'),
    path('statistics/', views.statistics_page, name='statistics'),
    path('register_event/<int:event_id>/', views.register_for_event, name='register_event'),
    path('unregister_event/<int:registration_id>/', views.unregister_from_event, name='unregister_event'),

    # path('profile/<str:username>', views.profile, name = 'profile'),
    # #path('editprofile/<str:username>', views.edit_profile, name = 'edit_profile'),
    # path('userprofiles/', views.user_profiles, name = 'user_profiles'),
]

templates/EMS/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <title> Tripobeat | {% block page-title %} {% endblock %} </title>
    <meta charset="utf-8">
    <meta name="description" content="The Homepage for Tripobeat">
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="{% static 'js/scripts.js' %}"></script>
    <!-- Below library is used for Social Media Icons -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="{% static 'css/login.css' %}">
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    <link rel="stylesheet" href="{% static 'css/event_registration.css' %}">
    <link rel="stylesheet" href="{% static 'css/home.css' %}">
    <link rel="stylesheet" href="{% static 'css/event_edit.css' %}">
    <link rel="stylesheet" href="{% static 'css/header.css' %}"> <!-- Add this line for header styles -->
    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>

</head>
<body>
<header class="header">
    <div class="header-left">
        <a href="{% url 'EMS:home_page' %}"><img src="{% static 'images/logo.png' %}" alt="EMS Logo" class="logo"></a>

    </div>
    <div class="header-center">
        <h1>EMS</h1>
    </div>
    <div class="header-right">
        <a href="{% url 'EMS:statistics' %}">
            <button class="profile-btn">Statistics</button>
        </a>
        <a href="{% url 'EMS:main' %}">
            <button class="profile-btn">Logout</button>
        </a>
    </div>
</header>
{% if messages %}
    <ul class="message-content">
        {% for message in messages %}
            <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
        {% endfor %}
    </ul>
{% endif %}
{% block content-text-block %}{% endblock %}
</body>
</html>