EMS/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include('EMS_app.urls', namespace='EMS')),

]

EMS_app/urls.py
from django.urls import path

from . import views

app_name = 'EMS'
# url patterns has list of all urls corresponding to the views and the webpages
urlpatterns = [
    path('', views.main, name='main'),
    path('login/organizer', views.login_page_organizer, name = 'login_page_organizer'),
    path('login/participant', views.login_page_participant, name = 'login_page_participant'),
    path('event_view/<int:event_id>/', views.event_view, name='event_view'),
    # path('logout/', views.logout_page, name= 'logout'),
    path('register/', views.register, name='register'),
    path('home/', views.home_page, name='home_page'),
    path('event_registration/', views.event_registration, name='event_registration'),
    path('event_edit/<int:id>', views.event_edit, name='event_edit'),
    path('delete_event/<int:id>', views.delete_event, name='delete_event'),
    path('statistics/', views.statistics_page, name='statistics'),
    path('register_event/<int:event_id>/', views.register_for_event, name='register_event'),
    path('unregister_event/<int:registration_id>/', views.unregister_from_event, name='unregister_event'),

    # path('profile/<str:username>', views.profile, name = 'profile'),
    # #path('editprofile/<str:username>', views.edit_profile, name = 'edit_profile'),
    # path('userprofiles/', views.user_profiles, name = 'user_profiles'),
]

templates/EMS/html_files/event_registration.html
{% extends "EMS/base.html" %}

{% load static %}

{% block page-title %}
Event Registration
{% endblock %}

{% block content-text-block %}
<body class="body">
    <div class="event-registration-box">
        <h1> Event Registration </h1>
         <form method="post" action="{% url 'EMS:event_registration' %}">
            {% csrf_token %}
            {{ form.as_div }}
        <button type="submit">Register Event</button>
        </form>
    </div>
</body>
{% endblock %}

templates/EMS/html_files/event_view.html
{% extends "EMS/base.html" %}
{% load static %}

{% block page-title %}
    Event Details
{% endblock %}

{% block content-text-block %}
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-6">
                <div class="card shadow">
                    <div class="card-body">
                        <h2 class="card-title">{{ event_name.name }}</h2>
                        <p class="card-text">{{ event_name.description }}</p>
                        <ul class="list-group list-group-flush">
                            <li class="list-group-item"><strong>Location:</strong> {{ event_name.location }}</li>
                            <li class="list-group-item"><strong>Start Date:</strong> {{ event_name.start_date|date:"D, d M Y H:i" }}</li>
                            <li class="list-group-item"><strong>End Date:</strong> {{ event_name.end_date|date:"D, d M Y H:i" }}</li>
                        </ul>

                        {% if is_registered and registration_status == "registered" %}
                            <form action="{% url 'EMS:unregister_event' registration_id %}" method="post">
                                {% csrf_token %}
                                <button type="submit" class="btn btn-warning">Unregister from Event</button>
                            </form>
                        {% elif not is_registered or registration_status == "unregistered" %}
                            {% if request.session.role == "participant" %}
                            <form action="{% url 'EMS:register_event' event_name.event_id %}" method="post">
                                {% csrf_token %}
                                <button type="submit" class="btn btn-primary">Register for Event</button>
                            </form>
                                {% endif %}
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/EMS/html_files/events_page.html
{% extends "EMS/base.html" %}

{% load static %}

{% block content-text-block %}
<body class="body">
    <div class="event-update-box">
        <h1> Update Event </h1>
         <form method="post">
            {% csrf_token %}
            {{ form.as_div }}
            <button type="submit">Update Event</button>
        </form>
    </div>
</body>
{% endblock %}

templates/EMS/html_files/home_page.html
{% extends "EMS/base.html" %}

{% load static %}

{% block page-title %}
    Home
{% endblock %}

{% block content-text-block %}
    <div class="container">
        <h3 class="alle-header"> All Events </h3>
        <div class="row">
            {% if request.session.role == "organizer" %}
                <div class="col-md-12">
                    <a href="{% url 'EMS:event_registration' %}" class="btn btn-primary mb-3">Create an Event</a>
                </div>
            {% endif %}
        </div>
        <div class="row">
            {% for event in events %}
                {% if forloop.counter0|divisibleby:4 %}
                    </div>
                    <div class="row">
                {% endif %}
                <div class="col-md-3 mb-4">
                    <div class="event-box">
                        <div class="event-header">
                            <a href="{% url 'EMS:event_view' event_id=event.event_id %}" class="event-name">
                                {{ event.name }}
                            </a>
                            <span class="registered-count">Registered Count: {{ event.count }}</span>
                        </div>


                        {% if request.session.role == "organizer" %}
                            <div class="event-actions">
                                <a href="{% url 'EMS:event_edit' event.event_id %}" class="btn btn-info btn-sm">Edit</a>
                                <a href="{% url 'EMS:delete_event' event.event_id %}" class="btn btn-danger btn-sm">Delete</a>
                            </div>
                        {% endif %}
                    </div>
                </div>
            {% endfor %}
            </div>
    </div>
{% endblock %}

templates/EMS/html_files/login_organizer.html
{% extends "EMS/base.html" %}


{% block content-text-block %}
<body class = "body">
    <div class="login-box">
        <h1> Login Page </h1>
        <form method="post" action = {% url "EMS:login_page_organizer" %}>
            {% csrf_token %}
            <label for="username">Username:</label>
            <input type="text" id="username" name="username" required>

            <label for="password">Password:</label>
            <input type="password" id="password" name="password" required>

            <button type="submit">Login</button>
            <div class = "signup-div">
            <a href="{% url "EMS:register" %}" class="signup-text">
                   Not a User? Sign Up.
            </a>
            </div>
        </form>
        {% if messages %}
            <ul class="message-content">
        {% for message in messages %}
        {{ message }}
        {% endfor %}
            </ul>
        {% endif %}
        {% if error_message %}
            <script>
                window.alert("{{ error_message }}");
            </script>
        {% endif %}
    </div>
</body>
{% endblock %}

templates/EMS/html_files/login_participant.html
{% extends "EMS/base.html" %}

{% block header %}
    {# Do nothing to override the header block #}
{% endblock %}

{% block content-text-block %}
<body class = "body">
    <div class="login-box">
        <h1> Login Page </h1>
        <form method="post" action = {% url "EMS:login_page_participant" %}>
            {% csrf_token %}
            <label for="username">Username:</label>
            <input type="text" id="username" name="username" required>

            <label for="password">Password:</label>
            <input type="password" id="password" name="password" required>

            <button type="submit">Login</button>
            <div class = "signup-div">
            <a href="{% url "EMS:register" %}" class="signup-text">
                   Not a User? Sign Up.
            </a>
            </div>
        </form>
        {% if messages %}
            <ul class="message-content">
        {% for message in messages %}
        {{ message }}
        {% endfor %}
            </ul>
        {% endif %}
        {% if error_message %}
            <script>
                window.alert("{{ error_message }}");
            </script>
        {% endif %}
    </div>
</body>
{% endblock %}

templates/EMS/html_files/main.html
{% load static %}


<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login Page</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
</head>
<body>
    <div class="container">
        <h1>Welcome to Event Management System</h1>
        <p>Please select an option:</p>
        <a href="{% url 'EMS:login_page_organizer' %}" class="btn">Login as Organizer</a>
        <a href="{% url 'EMS:login_page_participant' %}" class="btn">Login as Participant</a>
        <a href="{% url 'EMS:register' %}" class="btn">Sign Up</a>
    </div>
</body>
</html>

templates/EMS/html_files/register.html
{% extends "EMS/base.html" %}

{% load static %}

{% block page-title %}
Register
{% endblock %}

{% block content-text-block %}
<body class = "body">
    <div class="login-box">
    <h1> Registration Page </h1>
        <form method="post" action="{% url 'EMS:register' %}">
            {% csrf_token %}
            {{ form.as_div }}
        <button type="submit">Register</button>
            <div class = "login-link"><a href = "{% url 'EMS:main' %}"> Return to Login </a></div>
        </form>
        {% if error_message %}
            <script>
                window.alert("{{ error_message }}");
            </script>
        {% endif %}
    </div>
</body>
{% endblock %}

templates/EMS/html_files/statistics.html
{% extends "EMS/base.html" %}
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Event Statistics</title>
    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
    <link rel="stylesheet" href="{% static 'css/statistics.css' %}">


</head>
{% block content-text-block %}
<body>
<h1>Event Statistics</h1>

<section>
    <h3>Number of Events per Month</h3>
    <canvas id="eventsChart" width="400" height="200"></canvas>
</section>

<script type="text/javascript">
    document.addEventListener('DOMContentLoaded', function () {
        // Retrieve data for events by month chart
        const monthsData = JSON.parse(document.getElementById('months-data').textContent);
        const countsData = JSON.parse(document.getElementById('counts-data').textContent);

        // Render events by month chart
        const ctxEvents = document.getElementById('eventsChart').getContext('2d');
        const eventsChart = new Chart(ctxEvents, {
            type: 'bar',
            data: {
                labels: monthsData,
                datasets: [{
                    label: 'Events by Month',
                    data: countsData,
                    backgroundColor: 'rgba(54, 162, 235, 0.2)',
                    borderColor: 'rgba(54, 162, 235, 1)',
                    borderWidth: 1
                }]
            },
            options: {
                scales: {
                    y: {
                        beginAtZero: true
                    }
                }
            }
        });
    });
</script>

<script type="application/json" id="months-data">{{ months|safe }}</script>
<script type="application/json" id="counts-data">{{ counts|safe }}</script>

</body>
{% endblock %}
</html>